name: scidart
description: Cross-platform scientific library for Dart. The main goal of SciDart is run where Dart can run, in other words, run on Flutter, Dart CLI, Dart web, etc.
version: 0.0.2-dev.4
homepage: https://scidart.org/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
