name: scidart
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Ã‚ngelo Polotto <angelopolotto@yahoo.com.br>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  logging: ^0.11.3+2


dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
