name: scidart
description: Cross-platform scientific library for Dart. The main goal of SciDart is run where Dart can run, in other words, run on Flutter, Dart CLI, Dart web, etc.
version: 0.0.1-dev.6
homepage: https://scidart.org/
author: Ã‚ngelo Polotto <angelopolotto@gmail.com.br>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
